### ISSUE TITLE
Curated Block: Increase Minimum from 20 to 35

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-listings#94]
Local Profile has mentioned that 20 feels too few. They've requested 35. Would that be too much to load all at once? What's the best way for us to determine the optimal threshold for that setting?

**Comment by dkoo** [comment]
20 was an arbitrary limit, so it's good to hear some feedback from an actual use case. The limit exists to minimize performance-related issues due to large, complex DB queries, but there's no magic number when it comes to query performance. Let's try bumping the limit up to 50 and monitor Local Profile's site for performance-related issues on pages with the larger lists.
